const consentStep=document.querySelector('#consent-step'),recordStep=document.querySelector('#record-step');
const form=document.querySelector('#consent-form'),summary=document.querySelector('#consent-summary');
const recordButton=document.querySelector('#record-button'),stopButton=document.querySelector('#stop-button');
const statusEl=document.querySelector('#status'),timer=document.querySelector('#timer');
let metadata=null,recorder=null,chunks=[],startedAt=0,tick=null;

form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);metadata={speaker_id:data.get('speaker_id').trim(),dialect:data.get('dialect'),municipality:data.get('municipality').trim(),consent:{process_for_notes:data.has('process_for_notes'),retain_audio:data.has('retain_audio'),asr_training:data.has('asr_training'),tts_voice_training:data.has('tts_voice_training'),confirmation_method:data.get('confirmation_method'),form_version:'consent-v0.1-draft'}};summary.textContent=`${metadata.speaker_id} · ${metadata.dialect} · ASR: ${metadata.consent.asr_training?'sí':'no'} · TTS: ${metadata.consent.tts_voice_training?'sí':'no'}`;consentStep.hidden=true;recordStep.hidden=false;});

recordButton.addEventListener('click',async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.addEventListener('dataavailable',e=>{if(e.data.size)chunks.push(e.data)});recorder.addEventListener('stop',()=>save(stream));startedAt=Date.now();recorder.start();recordButton.disabled=true;stopButton.disabled=false;statusEl.textContent='Grabando...';tick=setInterval(()=>{const s=Math.floor((Date.now()-startedAt)/1000);timer.textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`},250)}catch(error){statusEl.textContent=`No se pudo usar el micrófono: ${error.message}`}});
stopButton.addEventListener('click',()=>{if(recorder?.state==='recording'){stopButton.disabled=true;recorder.stop();clearInterval(tick);statusEl.textContent='Guardando audio y metadatos...'}});
async function save(stream){const duration=(Date.now()-startedAt)/1000;stream.getTracks().forEach(track=>track.stop());const audio=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});const payload={...metadata,duration_seconds:duration,recorded_at:new Date().toISOString()};const body=new FormData();body.append('metadata',JSON.stringify(payload));body.append('audio',audio,'recording.webm');try{const response=await fetch('/api/recordings',{method:'POST',body});const result=await response.json();if(!response.ok)throw new Error(result.error||'Error del servidor');statusEl.textContent=`Guardado: ${result.recording_id}. Audio fuera de Git y metadatos en JSONL.`}catch(error){statusEl.textContent=`No se pudo guardar: ${error.message}`}finally{recordButton.disabled=false;timer.textContent='00:00'}}
document.querySelector('#reset-button').addEventListener('click',()=>{recordStep.hidden=true;consentStep.hidden=false;statusEl.textContent='El navegador pedirá permiso para usar el micrófono.';metadata=null});
